### ISSUE TITLE
NoSuchMethodError when used with liquibase 3.4.0

### ISSUE THREAD

**Issue by mjcramer** [cohenjo/liquibase-vertica#1]
Is there support for liquibase 3.4.0? I started getting this exception upon running update...

java.lang.NoSuchMethodError: liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getTables(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
	at liquibase.ext.vertica.snapshot.TableSnapshotGeneratorVertica.snapshotObject(TableSnapshotGeneratorVertica.java:46)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:60)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:194)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:70)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:44)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:21)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:150)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:158)
	at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:165)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:98)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1069)
	at liquibase.Liquibase.update(Liquibase.java:201)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:184)

**Comment by cohenjo** [comment]
Hi Michael,
I haven't ported the code to work with version 3.4 - I worked on 3.3, I guess the upgrade broke things :)

I'll make a 3.4 branch, to fix things - usually it's small changes so shouldn't take too long.

Thanks for reporting,
Regards,
 - Jony

**Comment by cohenjo** [comment]
Hi,
Could you please test using:
https://github.com/cohenjo/liquibase-vertica/tree/3.4

BTW, what version of Vertica are you using? (this code is designed for Vertica 7.1)
Regards,
 - Jony

**Comment by mjcramer** [comment]
Thanks for your prompt response! I'll try this out today. I'm using Vertica
JDBC 7.1.1-0 downloaded straight from HP.


-¢

**Comment by mjcramer** [comment]
Sorry to bother, but I cannot get any branch to build with maven:

[ERROR] Failed to execute goal on project liquibase-verticaDatabase: Could
not resolve dependencies for project
org.liquibase.ext:liquibase-verticaDatabase:jar:1.2-1: Could not find
artifact com.vertica:verticaDatabase:jar:6.1.2 in central (
https://repo.maven.apache.org/maven2) -> [Help 1]

I can't seem to find this dependency anywhere. In my vertica install, I see
a file called VerticaSDK.jar. Could that be the droid I'm looking for?

-c


-¢

**Comment by cohenjo** [comment]
Hi,
Sorry it's my mistake - it's a leftover from the internal maven we use here.
please remove it from the pom - Just make sure you have the Vertica jdbc driver.
I'll update the pom when I'll have a minute near my computer.

Sorry,
 - Jony

**Comment by Blackbaud-MikeLueders** [comment]
@cohenjo I can confirm this does work with liquibase 3.4 (at least for table creates), thank you!

Also, I've raised https://github.com/cohenjo/liquibase-vertica/pull/2 to resolve the pom dependency issue.

Cheers

**Comment by cohenjo** [comment]
Thanks for verifying (didn't have time to look into it lately... )
10x :)
